"""Domain Enums for the AI Revenue Recovery Orchestrator.

Locked Scope:
- Primary: Failed Payment Recovery
- Secondary: Recurring Subscription Payment Recovery
"""

from enum import Enum


class CaseType(str, Enum):
    ONE_TIME_PAYMENT = "ONE_TIME_PAYMENT"
    SUBSCRIPTION_RECURRING = "SUBSCRIPTION_RECURRING"


class FailureCategory(str, Enum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    EXPIRED_INSTRUMENT = "EXPIRED_INSTRUMENT"
    BANK_TIMEOUT_NETWORK = "BANK_TIMEOUT_NETWORK"
    AUTHENTICATION_OTP_FAILURE = "AUTHENTICATION_OTP_FAILURE"
    RISK_SECURITY_BLOCK = "RISK_SECURITY_BLOCK"
    MANDATE_EXPIRED_INVALID = "MANDATE_EXPIRED_INVALID"
    GENERAL_TECHNICAL_ERROR = "GENERAL_TECHNICAL_ERROR"


class RecoveryStrategy(str, Enum):
    """Locked Action Space.
    
    Primary: SMART_RETRY | PAYMENT_LINK | HUMAN_ESCALATION | STOP
    Secondary: SUBSCRIPTION_RETRY | UPDATE_PAYMENT_METHOD | HUMAN_ESCALATION | STOP
    """
    SMART_RETRY = "SMART_RETRY"
    PAYMENT_LINK = "PAYMENT_LINK"
    SUBSCRIPTION_RETRY = "SUBSCRIPTION_RETRY"
    UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    STOP = "STOP"


class CaseStatus(str, Enum):
    DETECTED = "DETECTED"
    DIAGNOSED = "DIAGNOSED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    ACTION_IN_PROGRESS = "ACTION_IN_PROGRESS"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    VERIFIED_RECOVERED = "VERIFIED_RECOVERED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"
    CLOSED_UNRECOVERABLE = "CLOSED_UNRECOVERABLE"


class PolicyOutcome(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    DOWNGRADE = "DOWNGRADE"
    ESCALATE = "ESCALATE"
    STOP = "STOP"


class TruthProvenance(str, Enum):
    LIVE_TEST_MODE_API_RESULT = "LIVE_TEST_MODE_API_RESULT"
    MOCKED_TEST_RESULT = "MOCKED_TEST_RESULT"
    SYNTHETIC_DATA_RESULT = "SYNTHETIC_DATA_RESULT"
